# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='wenzhang',
        ),
    ]
