# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-09 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20180507_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wenzhang',
            options={'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
        migrations.AddField(
            model_name='wenzhang',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
