# Generated by Django 2.0.4 on 2018-05-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zhuanjia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profname', models.CharField(max_length=200, verbose_name='专家名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
            ],
            options={
                'verbose_name': '专家信息',
                'verbose_name_plural': '专家信息',
            },
        ),
    ]
