# Generated by Django 2.0.4 on 2018-05-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhuanjia',
            name='quesnum',
            field=models.TextField(default='', verbose_name='向我提问的问题标号'),
            preserve_default=False,
        ),
    ]
