# Generated by Django 2.0.4 on 2018-05-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_zhuanjia_quesnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhuanjia',
            name='quesnum',
            field=models.TextField(null=True, verbose_name='向我提问的问题标号'),
        ),
    ]
