# Generated by Django 2.0.4 on 2018-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_auto_20180516_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhuanjia',
            name='quesnum',
            field=models.TextField(default='', verbose_name='向我提问的问题标号'),
        ),
    ]
