# Generated by Django 2.0.4 on 2018-05-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_auto_20180516_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhuanjia',
            name='quesnum',
            field=models.TextField(blank=True, null=True, verbose_name='向我提问的问题标号'),
        ),
    ]
