# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('article', models.TextField(verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u571f\u58e4',
                'verbose_name_plural': '\u571f\u58e4',
            },
        ),
        migrations.CreateModel(
            name='Shifei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('article', models.TextField(verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u65bd\u80a5',
                'verbose_name_plural': '\u65bd\u80a5',
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('article', models.TextField(verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u704c\u6c34',
                'verbose_name_plural': '\u704c\u6c34',
            },
        ),
    ]
