# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-09 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthandwater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earth',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='shifei',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='water',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
