# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sumjian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('article', models.TextField(verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u590f\u526a',
                'verbose_name_plural': '\u590f\u526a',
            },
        ),
        migrations.CreateModel(
            name='Winjian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('article', models.TextField(verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u51ac\u526a',
                'verbose_name_plural': '\u51ac\u526a',
            },
        ),
    ]
