# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-09 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumjian',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='winjian',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
