# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('article', models.TextField(verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u82b1\u671f',
                'verbose_name_plural': '\u82b1\u671f',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('article', models.TextField(verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u91c7\u6536',
                'verbose_name_plural': '\u91c7\u6536',
            },
        ),
        migrations.CreateModel(
            name='Tie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('article', models.TextField(verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u5957\u888b',
                'verbose_name_plural': '\u5957\u888b',
            },
        ),
        migrations.CreateModel(
            name='UnTie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('article', models.TextField(verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u89e3\u888b',
                'verbose_name_plural': '\u89e3\u888b',
            },
        ),
    ]
