# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-09 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindofearly',
            options={'verbose_name': '\u4e3b\u8981\u54c1\u79cd-\u65e9\u719f', 'verbose_name_plural': '\u4e3b\u8981\u54c1\u79cd-\u65e9\u719f'},
        ),
        migrations.AlterModelOptions(
            name='kindoflate',
            options={'verbose_name': '\u4e3b\u8981\u54c1\u79cd-\u665a\u719f', 'verbose_name_plural': '\u4e3b\u8981\u54c1\u79cd-\u665a\u719f'},
        ),
        migrations.AlterModelOptions(
            name='kindofmid',
            options={'verbose_name': '\u4e3b\u8981\u54c1\u79cd-\u4e2d\u719f', 'verbose_name_plural': '\u4e3b\u8981\u54c1\u79cd-\u4e2d\u719f'},
        ),
        migrations.AddField(
            model_name='kindofearly',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='kindoflate',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='kindofmid',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
