# Generated by Django 2.0.4 on 2018-05-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luntan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userinfo',
            new_name='luntan',
        ),
    ]
