# Generated by Django 2.0.4 on 2018-05-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luntan', '0002_auto_20180514_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='luntan',
            name='username',
            field=models.CharField(default='', max_length=200, verbose_name='用户'),
            preserve_default=False,
        ),
    ]
